/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DangNhapDAO;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.prefs.Preferences;


/**
 *
 * @author Admin
 */
public class frmDangNhap extends javax.swing.JFrame {
    /**
     * Creates new form frmDangNhap
     */
    private ImageIcon showIcon; // Icon cho trạng thái hiện mật khẩu
    private ImageIcon hideIcon; // Icon cho trạng thái ẩn mật khẩu
    private boolean isPasswordVisible = false; // Biến lưu trạng thái hiện tại của mật khẩu
    private Preferences prefs;
    public frmDangNhap() {
        initComponents();
        prefs = Preferences.userNodeForPackage(getClass());
        // Gọi phương thức để tải ảnh nền lên panel
        setBgImage();
        this.setLocationRelativeTo(null);
        // Khởi tạo hai icon cho hai trạng thái
        showIcon = new ImageIcon(getClass().getResource("/images/icon_show.png"));
        hideIcon = new ImageIcon(getClass().getResource("/images/icon_hide.png"));

        btnpass.setIcon(showIcon);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent windowEvent) {
                formWindowOpened(windowEvent);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        chkLuu = new javax.swing.JCheckBox();
        txtUser = new javax.swing.JTextField();
        btnpass = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Đăng nhập");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_user.png"))); // NOI18N
        lblUser.setToolTipText("");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_password.png"))); // NOI18N
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, -1));

        btnXacNhan.setBackground(new java.awt.Color(204, 204, 204));
        btnXacNhan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 110, 30));

        chkLuu.setText("Bạn có muốn lưu mật khẩu?");
        jPanel1.add(chkLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, -1));

        btnpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_hide.png"))); // NOI18N
        btnpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpassActionPerformed(evt);
            }
        });
        jPanel1.add(btnpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 20, 20));

        btnThoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_logout.png"))); // NOI18N
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 40, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Đăng ký");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, 30));
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát khỏi chương trình?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        String user = txtUser.getText();
        char[] passwordChars = txtPass.getPassword();
        String pass = new String(passwordChars);
        String tenNhanVien = DangNhapDAO.layTenNhanVien(user, pass);
        String layQuyenNhanVien = DangNhapDAO.layQuyenNhanVien(user, pass);
        if (tenNhanVien != null) {
            if (chkLuu.isSelected()) {
                prefs.putBoolean("REMEMBER_CHECKBOX", true);
                prefs.put("USERNAME", user);
                prefs.put("PASSWORD", pass);
            } else {
                prefs.putBoolean("REMEMBER_CHECKBOX", false);
                prefs.remove("USERNAME");
                prefs.remove("PASSWORD");
            }

            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
            frmTrangChu tc = new frmTrangChu(tenNhanVien, layQuyenNhanVien);
            tc.setVisible(true);
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng!");
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed
    private void formWindowOpened(java.awt.event.WindowEvent evt) {        
        boolean rememberChecked = prefs.getBoolean("REMEMBER_CHECKBOX", false);
        chkLuu.setSelected(rememberChecked);
        if (rememberChecked) {
            String savedUsername = prefs.get("USERNAME", "");
            txtUser.setText(savedUsername);
            String savedPassword = prefs.get("PASSWORD", "");
            txtPass.setText(savedPassword);
        }

    }     
    private void btnpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpassActionPerformed
        // TODO add your handling code here:
        isPasswordVisible = !isPasswordVisible;

        if (isPasswordVisible) {
            txtPass.setEchoChar('\u0000'); 
            btnpass.setIcon(showIcon);
        } else {
            txtPass.setEchoChar('*'); 
            btnpass.setIcon(hideIcon);
        }
    }//GEN-LAST:event_btnpassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        frmDangKy dk = new frmDangKy();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnpass;
    private javax.swing.JCheckBox chkLuu;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void setBgImage() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/background_login.jpg"));
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(new JLabel(icon));
    }
}
