/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.HangHoaDAO;
import DAO.NhaCungCapDAO;
import POJO.clsFormatCol;
import POJO.clsHangHoa;
import POJO.clsLoaiHang;
import POJO.clsNhaCungCap;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author Admin
 */
public class frmHangHoa extends javax.swing.JFrame {

    /**
     * Creates new form frmHangHoa
     */
    public frmHangHoa() {
        initComponents();
        
        btnTimKiem.setOpaque(false);
        btnTimKiem.setContentAreaFilled(false);
        
        btnThem.setOpaque(false);
        btnThem.setContentAreaFilled(false);
        
        btnXoa.setOpaque(false);
        btnXoa.setContentAreaFilled(false);
        
        btnSua.setOpaque(false);
        btnSua.setContentAreaFilled(false);
        
        btnLuu.setOpaque(false);
        btnLuu.setContentAreaFilled(false);
        
        
        this.setLocationRelativeTo(null);
        
        load_theloai();
        load_HangHoa();
        load_nhacungcap();
        TableColumnModel columnModel = tblHangHoa.getColumnModel();
        columnModel.getColumn(5).setCellRenderer(new clsFormatCol());
        columnModel.getColumn(7).setCellRenderer(new clsFormatCol());
        Enable(false);
        tblHangHoa.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHang = new javax.swing.JTextField();
        txtTenHang = new javax.swing.JTextField();
        txtDonViTinh = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtTonKho = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        cboLoaiHang = new javax.swing.JComboBox<>();
        btnLoaiHang = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        btnGetImages = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtHinhAnh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboNhaCungCap = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtKeyWord = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangHoa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 1030, 290));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hàng hóa"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã hàng:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 41, 65, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên hàng:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 90, 65, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Loại hàng:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Đơn vị tính:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng tồn:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giá nhập:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 61, -1));
        jPanel1.add(txtMaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 41, 40, -1));
        jPanel1.add(txtTenHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 90, 220, -1));
        jPanel1.add(txtDonViTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 70, -1));
        jPanel1.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, -1));
        jPanel1.add(txtTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 40, -1));
        jPanel1.add(txtGiaNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, -1));

        cboLoaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiHangActionPerformed(evt);
            }
        });
        jPanel1.add(cboLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 180, -1));

        btnLoaiHang.setText("...");
        btnLoaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoaiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 40, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 170, 140));

        btnGetImages.setText("Get");
        btnGetImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetImagesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Hình ảnh:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 60, -1));
        jPanel1.add(txtHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Nhà cung cấp:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, -1));

        cboNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNhaCungCapActionPerformed(evt);
            }
        });
        jPanel1.add(cboNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1030, 190));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_them.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 6, -1, -1));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_xoa.png"))); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 6, -1, -1));

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_sua.png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 6, -1, -1));

        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_luu.png"))); // NOI18N
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, -1, -1));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_timkiem.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 6, -1, -1));
        jPanel2.add(txtKeyWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 175, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 23));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_load.png"))); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_print.png"))); // NOI18N
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 40, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Enable(true);
        btnThem.setEnabled(false);
        txtMaHang.setEnabled(false);
        txtGiaNhap.setEnabled(false);
        txtMaHang.setText("");
        txtTonKho.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String key = txtKeyWord.getText();
        ArrayList<clsHangHoa> dsKQ = HangHoaDAO.timKiemHangHoaTheoTen(key);
        
        DefaultTableModel dtm = (DefaultTableModel)tblHangHoa.getModel();
        dtm.setRowCount(0);
        
        for(clsHangHoa hh : dsKQ)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(hh.getMaHang());
            vec.add(hh.getMaNCC());
            vec.add(hh.getTenHangHoa());
            vec.add(hh.getMaLoaiHang());
            vec.add(hh.getDonViTinh());
            vec.add(hh.getDonGia());
            vec.add(hh.getSoLuongTon());
            vec.add(hh.getGiaNhap());
            vec.add(hh.getHinhAnh());
            dtm.addRow(vec);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        Enable(true);
        txtMaHang.setEnabled(false);
        btnSua.setEnabled(false);
        txtGiaNhap.setEnabled(false);
        txtTonKho.setEnabled(false);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        try {
            
            String ten = txtTenHang.getText();
            clsLoaiHang selectedLoaiHang = (clsLoaiHang) cboLoaiHang.getSelectedItem();
            int maLH = selectedLoaiHang.getMa();
            clsNhaCungCap selectedNhaCC = (clsNhaCungCap) cboNhaCungCap.getSelectedItem();
            int maNCC = selectedNhaCC.getMaNCC();
            String donvitinh = txtDonViTinh.getText();
            String donGiaStr = txtDonGia.getText();
            String tonKhoStr = txtTonKho.getText();
            String giaNhapStr = txtGiaNhap.getText();
            String hinhAnh = txtHinhAnh.getText();

            if (ten.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tên hàng không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (donvitinh.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Đơn vị tính không được để trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int dongia;
            try {
                dongia = Integer.parseInt(donGiaStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Đơn giá phải là số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            clsHangHoa hh;
            
            if (txtMaHang.getText().isEmpty()) {
                hh = new clsHangHoa(maNCC, ten, maLH, donvitinh, dongia, hinhAnh);
                HangHoaDAO.themHangHoa(hh);
                btnThem.setEnabled(true);
                txtMaHang.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Thêm hàng hóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int ma = Integer.parseInt(txtMaHang.getText());
                int soluongton = Integer.parseInt(tonKhoStr);
//                try {
//                    soluongton = Integer.parseInt(tonKhoStr);
//                } catch (NumberFormatException e) {
//                    JOptionPane.showMessageDialog(this, "Số lượng tồn phải là số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }

                int gianhap = Integer.parseInt(giaNhapStr);;
//                try {
//                    gianhap = Integer.parseInt(giaNhapStr);
//                } catch (NumberFormatException e) {
//                    JOptionPane.showMessageDialog(this, "Giá nhập phải là số hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//                    return;
//                }
                hh = new clsHangHoa(ma, maNCC, ten, maLH, donvitinh, dongia,soluongton, gianhap, hinhAnh);
                HangHoaDAO.capNhatHangHoa(hh);
                txtMaHang.setEnabled(false);
                btnSua.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Cập nhật hàng hóa thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            updateTable();
            Enable(false);
            Reset();

        } catch (Exception ex) {
            Logger.getLogger(frmHangHoa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblHangHoa.getSelectedRow();

        if (rowIndex >= 0) {
            int maHang = (int) tblHangHoa.getValueAt(rowIndex, 0);

            clsHangHoa hh = HangHoaDAO.layHangHoa(maHang);
            txtMaHang.setText(String.valueOf(hh.getMaHang()));
            
            txtTenHang.setText(hh.getTenHangHoa());

            for (int i = 0; i < cboLoaiHang.getItemCount(); i++) {
                clsLoaiHang loaiHang = (clsLoaiHang) cboLoaiHang.getItemAt(i);
                if (loaiHang.getMa() == hh.getMaLoaiHang()) {
                    cboLoaiHang.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < cboNhaCungCap.getItemCount(); i++) {
                clsNhaCungCap nhaCC = (clsNhaCungCap) cboNhaCungCap.getItemAt(i);
                if (nhaCC.getMaNCC() == hh.getMaNCC()) {
                    cboNhaCungCap.setSelectedIndex(i);
                    break;
                }
            }
            txtDonViTinh.setText(hh.getDonViTinh());
            txtDonGia.setText(String.valueOf(hh.getDonGia()));
            txtTonKho.setText(String.valueOf(hh.getSoLuongTon()));
            txtGiaNhap.setText(String.valueOf(hh.getGiaNhap()));
            txtHinhAnh.setText(hh.getHinhAnh());
            String imageName = (String) tblHangHoa.getValueAt(rowIndex, 8);

            // Tạo đường dẫn tương đối
            String imagePath = imageName;

            setImage(imagePath);
            
        }
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int maHH = Integer.parseInt(txtMaHang.getText());
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa hàng hóa có mã " + maHH + " không?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE);
        boolean result = HangHoaDAO.xoaHangHoa(maHH);
        if (confirm == JOptionPane.YES_OPTION) {
            if(result)
            {
                updateTable();
                Reset();
                JOptionPane.showMessageDialog(this, "Xóa thành công mã hàng " + maHH);

            }else
            {
                JOptionPane.showMessageDialog(this, "Xóa không thành công mã hàng " + maHH);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnGetImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetImagesActionPerformed
        // TODO add your handling code here:
        // Tạo một hộp thoại chọn tệp
        JFileChooser fileChooser = new JFileChooser();

        String currentDir = System.getProperty("user.dir") + "/images";
        fileChooser.setCurrentDirectory(new File(currentDir));

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String imagePath = "/images/" + selectedFile.getName();

            txtHinhAnh.setText(imagePath);
            setImage(imagePath);
        }
    }//GEN-LAST:event_btnGetImagesActionPerformed

    private void btnLoaiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiHangActionPerformed
        // TODO add your handling code here:
        frmLoaiHang lh = new frmLoaiHang();
        lh.setVisible(true);
    }//GEN-LAST:event_btnLoaiHangActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Lưu tệp Excel");

        // Đặt bộ lọc tệp Excel
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra phần mở rộng của tệp
            String extension = "";

            int i = filePath.lastIndexOf('.');
            int p = Math.max(filePath.lastIndexOf('/'), filePath.lastIndexOf('\\'));

            if (i > p) {
                extension = filePath.substring(i + 1);
            }

            if (!extension.equalsIgnoreCase("xlsx")) {
                filePath += ".xlsx"; // Nếu không có phần mở rộng, thêm ".xlsx" vào cuối tên tệp
            }

            exportToExcel(tblHangHoa, filePath);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void cboLoaiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiHangActionPerformed

    private void cboNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNhaCungCapActionPerformed
    public void exportToExcel(JTable table, String filePath) {
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Danh sách hàng hóa");

            int rowCount = table.getRowCount();
            int columnCount = table.getColumnCount();

            XSSFRow headerRow = sheet.createRow(0);
            for (int j = 0; j < columnCount; j++) {
                headerRow.createCell(j).setCellValue(table.getColumnName(j));
            }

            for (int i = 0; i < rowCount; i++) {
                XSSFRow row = sheet.createRow(i + 1);
                for (int j = 0; j < columnCount; j++) {
                    row.createCell(j).setCellValue(String.valueOf(table.getValueAt(i, j)));
                }
            }
            XSSFRow countRow = sheet.createRow(rowCount + 1);
            countRow.createCell(columnCount - 1).setCellValue("Số mặt hàng:");
            countRow.createCell(columnCount).setCellValue(rowCount);

            try (FileOutputStream outputStream = new FileOutputStream(filePath)) {
                workbook.write(outputStream);
            }

            System.out.println("Exported to Excel successfully.");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHangHoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHangHoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetImages;
    private javax.swing.JButton btnLoaiHang;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<clsLoaiHang> cboLoaiHang;
    private javax.swing.JComboBox<clsNhaCungCap> cboNhaCungCap;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtHinhAnh;
    private javax.swing.JTextField txtKeyWord;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables
    private void Enable(boolean check)
    {
        txtMaHang.setEnabled(check);
        txtDonGia.setEnabled(check);
        txtDonViTinh.setEnabled(check);
        txtGiaNhap.setEnabled(check);
        cboLoaiHang.setEnabled(check);
        cboNhaCungCap.setEnabled(check);
        txtTenHang.setEnabled(check);
        txtTonKho.setEnabled(check);
        btnLuu.setEnabled(check);
        txtHinhAnh.setEnabled(check);
    }
    private void Reset() {
        txtTenHang.setText("");
        txtDonViTinh.setText("");
        txtDonGia.setText("");
        txtTonKho.setText("");
        txtGiaNhap.setText("");
        txtHinhAnh.setText("");

        if (cboLoaiHang.getItemCount() > 0) {
            cboLoaiHang.setSelectedIndex(0);
        }
        if (cboNhaCungCap.getItemCount() > 0) {
            cboNhaCungCap.setSelectedIndex(0);
        }
        txtMaHang.setText("");
        String imagePath = txtHinhAnh.getText();
        setImage(imagePath);
    }

    public void updateTable()
    {
        ArrayList<clsHangHoa> dsHH = HangHoaDAO.layDanhSachHangHoa();
        DefaultTableModel dtm = (DefaultTableModel)tblHangHoa.getModel();
        
        dtm.setRowCount(0);
        for(clsHangHoa hh : dsHH)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(hh.getMaHang());
            vec.add(hh.getMaNCC());
            vec.add(hh.getTenHangHoa());
            vec.add(hh.getMaLoaiHang());
            vec.add(hh.getDonViTinh());
            vec.add(hh.getDonGia());
            vec.add(hh.getSoLuongTon());
            vec.add(hh.getGiaNhap());
            vec.add(hh.getHinhAnh());
            dtm.addRow(vec);
        }
    }
    public void load_theloai() {
        ArrayList<clsLoaiHang> ds = HangHoaDAO.layLoaiHang();
        DefaultComboBoxModel<clsLoaiHang> model = new DefaultComboBoxModel<>();

        for (clsLoaiHang x : ds) {
            model.addElement(x); 
        }

        cboLoaiHang.setModel(model);
        cboLoaiHang.setSelectedIndex(0); 
    }
    public void load_nhacungcap() {
        ArrayList<clsNhaCungCap> ds = NhaCungCapDAO.layNhaCungCap();
        DefaultComboBoxModel<clsNhaCungCap> model = new DefaultComboBoxModel<>();

        for (clsNhaCungCap x : ds) {
            model.addElement(x); 
        }
        cboNhaCungCap.setModel(model);
        cboNhaCungCap.setSelectedIndex(0);
    }
    public void load_HangHoa()
    {
        String []TieuDe = {"Mã hàng hóa","Nhà cung cấp" ,"Tên hàng hóa", "Loại hàng", "Đơn vị tính", "Đơn giá", "Số lượng tồn", "Giá nhập", "Hình ảnh"};
        DefaultTableModel dtm = (DefaultTableModel)tblHangHoa.getModel();
        dtm.setColumnIdentifiers(TieuDe);
        dtm.setRowCount(0);
        ArrayList<clsHangHoa> dsHH = HangHoaDAO.layDanhSachHangHoa();
        for(clsHangHoa hh : dsHH)
        {
            Vector<Object> vec = new Vector<Object>();
            vec.add(hh.getMaHang());
            vec.add(hh.getMaNCC());
            vec.add(hh.getTenHangHoa());
            vec.add(hh.getMaLoaiHang());
            vec.add(hh.getDonViTinh());
            vec.add(hh.getDonGia());
            vec.add(hh.getSoLuongTon());
            vec.add(hh.getGiaNhap());
            vec.add(hh.getHinhAnh());
            dtm.addRow(vec);
        }
        tblHangHoa.setModel(dtm);
    }
    private void setImage(String imagePath) {
        if (imagePath != null && !imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            Image image = icon.getImage().getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
            imageLabel.setIcon(new ImageIcon(image));
        } else {
            // Nếu không có đường dẫn hình ảnh, đặt hình ảnh mặc định hoặc trống
            imageLabel.setIcon(null);
            
        }
    }
}
